---
- name: include os dependent vars file
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: include install.yml
  import_tasks: install.yml
  tags:
    - auditd_install

- name: include configure.yml
  import_tasks: configure.yml
  tags:
    - auditd_configure
