---
- name: restart auditd
  service:
    name: auditd
    state: restarted
    use: service

- name: reload auditd
  service:
    name: auditd
    state: reloaded
    use: service

- name: load rules
  service:
    name: auditd
    state: reloaded
    use: service
