---
- name: restart auditd
  service:
    name: auditd
    state: restarted
    use: service
  become: true
  when:
    - ansible_virtualization_type != "docker"

- name: run augenrules
  command: augenrules
  notify: load rules
  become: true

- name: load rules
  command: augenrules --load
  become: true
  when:
    - ansible_virtualization_type != "docker"
