---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt upgrade -y && apt install -y python-minimal)
      become: true
      changed_when: false
      when: ansible_os_family == "Debian"
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (yum -y update && yum -y install python3)
      become: true
      changed_when: false
      when: ansible_os_family == "RedHat"
